### ISSUE TITLE
Produced Makefile doesn't contain include statement for headers from SHEDSKIN_LIBDIR

### ISSUE THREAD

**Issue by yurivict** [shedskin/shedskin#470]
make fails like this:
```
$ make
cc  -I/usr/local/include -O2 -std=c++17 -march=native  /usr/ports/devel/shed-skin/x/main.cpp  /usr/local/lib/python3.9/site-packages/shedskin/lib/builtin.cpp -L/usr/local/lib -lgc -lgctba -lutil  -o main
/usr/ports/devel/shed-skin/x/main.cpp:1:10: fatal error: 'builtin.hpp' file not found
    1 | #include "builtin.hpp"
      |          ^~~~~~~~~~~~~
1 error generated.
```

You need to add -I$(SHEDSKIN_LIBDIR) to CCFLAGS in the file FLAGS.

**Comment by srepmub** [comment]
hmm, this should already be appended automatically.. here in shedskin/makefile.py:

```
        if variable == "CCFLAGS":
            line += " -I. -I%s" % env_var("SHEDSKIN_LIBDIR")
```

**Comment by yurivict** [comment]
This works in 0.9.9
It was either a mistake in the OP, or there was some change that fixed it.

Thank you.
