### ISSUE TITLE
Simple os.popen() call fails to compile on Ubuntu Linux 13.04 64bit

### ISSUE THREAD

**Issue by ShedskinBot** [shedskin/shedskin#191]
**Issue by yassen....@gmail.com**
_28 Jun 2013 at 9:11 GMT_
_Originally opened on Google Code_

----

```
A simpe script like this one:

----cut here--------------------------------
import os
print os.popen("echo Hello World").read()
----cut here--------------------------------

translates fine but then fails to compile with the following output:

/root/Work/space/eclipse3.8/Trial/src/snapper/cpuinfo/cpuinfo.cpp: In function 
‘void __cpuinfo__::__init()’:
/root/Work/space/eclipse3.8/Trial/src/snapper/cpuinfo/cpuinfo.cpp:21:46: error: 
‘default_2’ is not a member of ‘__os__’


What steps will reproduce the problem?
1. Install latest shedskin (0.9.4 as of time of this writing);
2. Create and translate the above given script;
3. do $ make


-- What is the expected output? What do you see instead?

The expected output is a 'Hello world' string appearing.
It does not compile, failing with the above given error.

-- What version of the product are you using? On what operating system?

0.9.4 (latest stable as of this writing)
Linux 3.8.0-25-generic #37-Ubuntu SMP Thu Jun 6 20:47:07 UTC 2013 x86_64 x86_64 
x86_64 GNU/Linux



Please provide any additional information below.

```

**Comment by ShedskinBot** [comment]
**Comment by [Mark Dufour](/srepmub)**
_29 Jun 2013 at 8:27 GMT_

----

```
thanks for reporting! I can reproduce the problem here.. workaround for now is 
to explicitly pass a second argument to popen, such as "r". we will fix this 
shortly in git.

```


* Changed state: **Accepted**

**Comment by ShedskinBot** [comment]
**Comment by yassen....@gmail.com**
_30 Jun 2013 at 3:53 GMT_

----

```
Mark, thanks for your prompt reply! Yes, the workaround works. Your support is 
very much appreciated. Looking forward for the fix.

(BTW, I keep eyes on shedskin for quite some time and it now really seems to 
gain momentum ... Thank you for a great piece of software, keep up the good 
work!)
```

**Comment by ShedskinBot** [comment]
**Comment by [Mark Dufour](/srepmub)**
_1 Jul 2013 at 7:36 GMT_

----

```
not sure about the momentum, but ernesto just fixed the problem in shedskin 
git! :) thanks again for reporting, and please let us know if you run into 
anything else..
```


* Changed state: **Fixed**

**Comment by ShedskinBot** [comment]
**Comment by yassen....@gmail.com**
_12 Jul 2013 at 8:40 GMT_

----

```
Thanks guys for your awesome support! Keep up the good work! Y.
```
